- hosts: all
  tasks:
  - name: Disable root login over SSH without password
    lineinfile: dest=/etc/ssh/sshd_config regexp="^PermitRootLogin" line="PermitRootLogin prohibit-password" state=present
    notify:
      - restart sshd

- name: Set authorized keys for root
  ansible.posix.authorized_key:
    user: root
    state: present
    key: "{{ lookup('file', 'files/public_keys/id_phochs') }}"

  handlers:
  - name: restart sshd
    service:
      name: sshd
      state: restarted
