---
- hosts: all
  remote_user: root
  gather_facts: false
  serial:
    - 1
    - 2
    - 3
    - 5
    - 8
    - 13
    - 21
    - 34
    - 55
    - 89
    - "100%"
  tasks:
  - name: Update all packages
    apt:
      name: "*"
      state: latest
      update_cache: yes
