---
- hosts: all
  gather_facts: false
  remote_user: root
  vars:
    openssl_packages:
      - openssl
      - libssl1.1
    openssl_services:
      - nginx
      - apache2
      - lighttpd
      - php7.3-fpm
      - postfix

  tasks:
    - name: openssl lastest version
      apt: pkg={{item}} state=latest update_cache=yes
      register: openssl_updated
      loop: "{{ openssl_packages }}"

    - name: test running services
      command: "service {{item}} status | grep -i running"
      register: openssl_services
      loop: "{{ openssl_services }}"
      when: openssl_updated.changed
      ignore_errors: true

    - name: restart services
      service: name={{item.item}} state=restarted
      loop: "{{ openssl_services.results }}"
      when: openssl_updated.changed and item.rc == 0
